### ISSUE TITLE
support opening a folder not in the same directory as the .git folder

### ISSUE THREAD

**Issue by M-Zuber** [differentmatt/vscode-copy-github-url#10]
we have a monorepo that is not using submodules
In order to get other extensions to work, I open each subfolder in a different instance of vs code, but this then causes this extension to not be able to pick up the url.

If possible it would be nice to have a setting where I could set the path to the .git folder

**Comment by differentmatt** [comment]
Sounds like a good improvement.

I won't have time to add this in the near future, but would be happy to review a pull request for this update :)

________________________________
