### ISSUE TITLE
Slashes are flipped

### ISSUE THREAD

**Issue by M-Zuber** [differentmatt/vscode-copy-github-url#2]
When copying an url I got something like `https://github.com/M-Zuber/octokit.net/blob/master\Octokit\Clients\Enterprise\EnterpriseClient.cs#L9` instead of `https://github.com/M-Zuber/octokit.net/blob/master/Octokit/Clients/Enterprise/EnterpriseClient.cs#L9`

This is on Windows 10 if that makes a difference

**Comment by differentmatt** [comment]
I've published a fix.  Please let me know if you're still having problems.

Thanks for trying this on Windows!

**Comment by M-Zuber** [comment]
Works like a charm.
Thank you for the fast pickup!
