### ISSUE TITLE
Doesn't seem to work on Mac

### ISSUE THREAD

**Issue by iAmMichaelConnor** [differentmatt/vscode-copy-github-url#25]
Just installed the extension. ^ + L C (macOS's version of ctrl + L C) doesn't seem to do anything. I've checked the keybindings in VScode and ^ + L C is indeed bound to this extension. If I try and paste, then it pastes what was previously in my clipboard; not the GitHub url.

**Comment by differentmatt** [comment]
Closing this for now, but feel free to reopen.

**Comment by maztak** [comment]
Same here, but solved.
If you type `Control + Shift + L` and type only `c`.  Don't use `Command` key, and type nothing when u type `c`. 
When u type `Control + Shift + L`, VSCode shows it in footer area like this.
<img width="410" alt="スクリーンショット 2022-04-20 17 32 04" src="https://user-images.githubusercontent.com/36877670/164186279-b3d684e7-e6be-4a69-b2aa-6dafa1632298.png">
