### ISSUE TITLE
Ctrl+Shift+L keybinding conflicts

### ISSUE THREAD

**Issue by Noitidart** [differentmatt/vscode-copy-github-url#7]
Hi there, there is a default for `Ctrl+Shift+L` to select all highlighted instances.

May you please change it to `Ctrl+Alt+L`. Otherwise I have to put two extra keybindings in custom. One to Restore `Ctrl+Shift+L` to `{ "key": "ctrl+shift+l", "command": "editor.action.selectHighlights", "when": "editorFocus" }` and another to make this extension work: `{ "key": "ctrl+alt+l c", "command": "extension.gitHubUrlPerma", "when": "editorTextFocus" }`

**Comment by mlewand** [comment]
@Noitidart just keep in mind that typically it's a tough call to find a reasonable unused hotkey. And taking into account how easy it is to customize keys in vscode I would say it's not a big deal, especially given that selectHighlights is not sth as common as copy, change tab etc.

**Comment by differentmatt** [comment]
@Noitidart what do you suggest for a new default keybinding?

I'm probably going to leave the default keybindings as is for the reasons @mlewand suggested, and I don't want to break existing users of this extension.

**Comment by Noitidart** [comment]
I actually switched to mac. And am absolutely loving the default keybindings. The only issue is Ctrl + Left/Right (I am trying to figure out how to disable the desktop global hotkey so that vscode can use it)

**Comment by differentmatt** [comment]
Ah, excellent!

Not sure how to modify global hotkeys on mac, sorry :)
