### ISSUE TITLE
Not working on VSCode 1.17.2

### ISSUE THREAD

**Issue by cmalard** [differentmatt/vscode-copy-github-url#8]
Hello there,

Can't make it work, with command line or shortcut.
Nothing happens, I don't see any error in VSCode console output.

**Comment by differentmatt** [comment]
Hey @cmalard, is this still a problem in VSCode 1.18.0?

I'm not seeing the problem on my Mac.  What OS are you using?

**Comment by cmalard** [comment]
Hi @differentmatt , just tested on 1.18.1: still nothing happens.
My OS is Ubuntu 16.04 LTS.

**Comment by differentmatt** [comment]
Thanks for checking, not sure anyone's tried it on Ubuntu before.  I'll look into it.  Thanks!

**Comment by differentmatt** [comment]
Hey @cmalard, this extension will probably work if you install xclip manually, `sudo apt-get install xclip`.  If that doesn't work, please let me know.  Thanks!

The [copy-paste](https://github.com/xavi-/node-copy-paste/issues/57) package used in this extension relies on xclip being installed on Linux, unfortunately.

**Comment by cmalard** [comment]
Hey @differentmatt , ok, thanks for notifying.

Could you consider using [clipboardy](https://github.com/sindresorhus/clipboardy) instead of `copy-paste` ?
>It is more actively maintained and it fixes many of that module's issues.
https://stackoverflow.com/a/43153941/2787235

**Comment by differentmatt** [comment]
@cmalard sure, if clipboardy works better I'd be happy to switch.  I won't have time to make the change in the immediate future, but I'd be happy to review a PR :)
